version: 2
updates:
  # Weekly checks for nuget package updates
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    groups:
      npm-dependencies:
        patterns:
          - '*' # Group all updates together
